# storing birthdays inside five different variables 
print("Hello, Today we're going to store birthdays of Raj's five friends.")
print("Raj has five friends, Ekansh, Shahraan, Nayanti, Krishang and Sakshat.")
ekansh_birthday = str("5th June 2012")
shahraan_birthday = str("9th March 2012")
nayanti_birthday = str("30th September 2012")
krishang_birthday = str("24th May 2012")
sakshat_birthday = str("18th July 2012")
print("Ekansh's Birthday is on :", ekansh_birthday)
print("Shahraan's Birthday is on :", shahraan_birthday)
print("Nayanti's Birthday is on :", nayanti_birthday)
print("Krishang's Birthday is on :", krishang_birthday)
print("Sakshat's Birthday is on :", sakshat_birthday)
print("These were the birthdays of Raj's five friends.")
